#!/usr/bin/env bash
set -euo pipefail

# Scaffolds a consumer flake in the gitignored consumer/ directory that
# imports nixcfg as a flake input and composes its library surface — the
# external-consumer validation harness for the profiles refactor. Based on
# numtide/blueprint's home-manager-standalone structure (hosts/<host>/users/
# <user>.nix -> homeConfigurations."<user>@<host>").
#
# Usage: generate-consumer-flake.sh [hostname] [username]
# Defaults: myhost / me. Re-runnable; overwrites the generated tree.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT_DIR="${OUT_DIR:-$(dirname "$REPO_ROOT")/nixcfg-consumer}"

HOSTNAME_ARG="${1:-myhost}"
USERNAME_ARG="${2:-me}"

mkdir -p "$OUT_DIR/hosts/$HOSTNAME_ARG/users"

cat > "$OUT_DIR/flake.nix" <<EOF
{
  # Consumer flake generated by nixcfg's generate-consumer-flake.sh.
  # Structure from numtide/blueprint (home-manager standalone template):
  # hosts/<host>/users/<user>.nix maps to homeConfigurations."<user>@<host>".
  inputs = {
    # gnome-workstation targets Linux; pin the consumer to x86_64-linux
    systems.url = "github:nix-systems/x86_64-linux";

    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";

    blueprint = {
      url = "github:numtide/blueprint";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Local path for validation against the working tree; swap for
    # github:tcarrio/nixcfg when consuming for real.
    nixcfg = {
      url = "path:$REPO_ROOT";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs: inputs.blueprint { inherit inputs; };
}
EOF

cat > "$OUT_DIR/hosts/$HOSTNAME_ARG/users/$USERNAME_ARG.nix" <<EOF
{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:
{
  # nixcfg library modules (oxc.* options)
  imports = [ inputs.nixcfg.homeManagerModules.default ];

  home.stateVersion = "24.05";

  # nixcfg library surface: overlays supply pkgs.unstable (catppuccin-gtk
  # theme default) and the custom packages (nixvim).
  nixpkgs.overlays = [
    inputs.nixcfg.overlays.additions
    inputs.nixcfg.overlays.unstable-packages
  ];
  nixpkgs.config = {
    allowUnfree = true;
    allowUnfreePredicate = _: true;
  };

  # The oxc GNOME workstation profile: console (git/fish/direnv/
  # modern-unix/tools/neovim/tmux/atuin/gh), desktop set (ghostty with
  # pinned Catppuccin themes, emote, neovide, xresources), GNOME theming
  # (dark Catppuccin GTK), session nix-profile visibility, and rebuild
  # aliases. Everything greybox runs, minus personal identity.
  oxc.profiles.gnome-workstation = {
    enable = true;
    flakeTarget = "$USERNAME_ARG@$HOSTNAME_ARG";
  };

  # Consumer identity
  oxc.console.git = {
    userName = "Example User";
    userEmail = "me@example.com";
  };

  # Apt composition: converged on activation, stock-repo example package
  oxc.apt.onActivation.enable = true;
  oxc.apt.packages = [ "cachefilesd" ];

  # Lean-footprint trims, mirroring greybox's opt-outs
  oxc.console.modern-unix.extras = false;
  oxc.console.tools.eza = false;
}
EOF

echo "Generated consumer flake in $OUT_DIR (outside the repo: nix refuses"
echo "untracked paths inside a git tree, so gitignoring in-repo is not enough)"
echo "First run / after nixcfg changes: refresh the path input lock:"
echo "  (cd $OUT_DIR && nix flake update nixcfg)"
echo "Validate (blueprint nests homeConfigurations per system):"
echo "  nix eval $OUT_DIR#legacyPackages.x86_64-linux.homeConfigurations.\"$USERNAME_ARG@$HOSTNAME_ARG\".activationPackage.drvPath"
