name = "object-server"
main = "src/index.tsx"
compatibility_date = "2024-11-27"
# compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "nixos-images"

[env.dev]
route = { pattern = "dev-images.carrio.dev", custom_domain = true }

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
