_: {
  imports = [
    ./beeper.nix
    ./bitwarden.nix
    ./brave.nix
    ./chromium.nix
    ./cinny.nix
    ./daw.nix
    ./discord.nix
    ./element.nix
    ./emacs.nix
    ./ente.nix
    ./evolution.nix
    ./firefox.nix
    ./fonts.nix
    ./fractal.nix
    ./google-chrome.nix
    ./logseq.nix
    ./lutris.nix
    ./microsoft-edge.nix
    ./obs-studio.nix
    ./opera.nix
    ./simple-scan.nix
    ./spotify.nix
    ./steam.nix
    ./tilix.nix
    ./vivaldi.nix
    ./vscode.nix
    ./zed.nix
    ./zen-browser.nix
  ];
}
